import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  loading: {
    flex: 1,
    backgroundColor: "#1c2128",
    color: "white",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  heading : {
    fontSize: 30.0,
    color: "#1EC9E9",
    fontWeight: "bold",
    marginBottom: 12.0,
    borderBottomColor: "white",
    borderBottomWidth: 1.0,
    paddingBottom: 8.0,
  },
  container: {
    padding: 12.0,
    paddingTop: 24.0,
    flex: 1,
    backgroundColor: "#1c2128",
    color: "white",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
  },
  containerCard: {
    paddingVertical: 12.0,
    paddingHorizontal: 8.0,
    width: "100%",
    backgroundColor: "rgba(77,83,90,1)",
    borderRadius: 8.0,
    color: "white",
    shadowColor: "#000",
    shadowOpacity: 0.9,
    elevation: 20,
    borderColor: "white",
    borderWidth: 1.0,
    position: "relative",
    marginTop: 20.0,
    
  },
  containerCardHeader: {
    fontSize: 24.0,
    color: "#e91e63",
    fontWeight: "bold",
    marginBottom: 8.0,
    borderBottomColor: "white",
    borderBottomWidth: 1.0,
    paddingBottom: 8.0,
    
  },
  containerCardContent: {
    fontSize: 15.0,
    marginBottom: 3.0,
    padding: 4.0,
    textTransform: "capitalize",
    fontWeight: "bold",
    color: "#1EC9E9",
  },
  textHeader: {
    fontSize: 24.0,
    color: "#1EC9E9",
    fontWeight: "bold",
  },
  input: {
    backgroundColor: "#4d535a",
    color: "white",
    paddingHorizontal: 12.0,
    paddingVertical: 8.0,
    borderRadius: 8.0,
    marginBottom: 8.0,
    position: "relative",
    textAlign:"left",
    width: "100%",
    shadowColor: "#000",
    shadowOpacity: 0.9,
    elevation: 20,
    
  },
  textInputLabel: {
    fontSize: 20.0,
  },
  button: {
    backgroundColor: "#e91e63",
    paddingHorizontal: 12.0,
    paddingVertical: 8.0,
    borderRadius: 16.0,
    width: 128.0,
  },
  buttonText: {
    color: "white",
    textAlign: "center",
  },
  image: {
    width: '100%', // '100%' is the same as '100%
    height: 128.0,
    borderRadius: 8.0,
    resizeMode: "cover",
  },
  picker : {
    backgroundColor: "#1EC9E9",
    paddingHorizontal: 12.0,
    paddingVertical: 8.0,
    borderRadius: 8.0,
    marginBottom: 8.0,
  },
  pickerItem : {
    fontSize: 20.0,
  },
  emoji: {
    fontSize: 20.0,
    color: "#1EC9E9",
    fontWeight: "bold",
    marginBottom: 8.0,
  },
  modal: {
    backgroundColor: "#1c2128",
    padding: 12.0,
    maxHeight: 175.0,
    display: "flex",
    flexDirection: "column",
    width: "100%",
    alignSelf:"stretch",
    zIndex: 999,
    borderBottomColor: "white",
    borderBottomWidth: 2.0,
    paddingBottom: 8.0,
    shadowColor: "#000",
    shadowOpacity: 0.9,
    elevation: 25,

  },
  modalItem: {
    fontSize: 20.0,
    color: "white",
    marginBottom: 6.0,
    padding: 4.0,
    textTransform: "capitalize",
    fontWeight: "bold",
    width: "100%",
    backgroundColor: "#22272e",
    borderRadius: 8.0,
    borderColor: "white",
    borderWidth: 1.0,
    shadowColor: "white",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8.0,
    elevation: 5,
  },
  modalItemText: {
    fontSize: 16.0,
    color: "white",
    marginBottom: 6.0,
    padding: 4.0,
    textTransform: "capitalize",
    fontWeight: "bold",
    width: "100%",
  },
  error: {
    color: "red",
    fontSize: 12.0,
    marginBottom: 8.0,
  },
  inputContainer: {
    width: "100%",
    marginBottom: 8.0,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    color: "white",
  },
  inputText: {
    fontSize: 20.0,
    color: "#e91e63",
    fontWeight: "bold",
  },
});

export default styles;
